# --------------------------------
# Application
# --------------------------------
spring.application.name=kafka-order-service
server.port=8081

# --------------------------------
# Kafka Bootstrap
# --------------------------------
spring.kafka.bootstrap-servers=localhost:9092

# --------------------------------
# Producer Configuration
# --------------------------------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer