# -----------------------------
# Application Configuration
# -----------------------------
spring.application.name=kafka-payment-service
server.port=8082

# -----------------------------
# Kafka Bootstrap Server
# -----------------------------
spring.kafka.bootstrap-servers=localhost:9092

# -----------------------------
# Consumer Configuration
# -----------------------------
spring.kafka.consumer.group-id=payment-group1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true

# Key & Value Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell Kafka which class to convert JSON into
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.kafka.payment.service.model.Order

# -----------------------------
# (Optional) Producer Config
# Only needed if this service also produces messages
# -----------------------------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer